// Fixture catalogue used by the tests in place of the live Supabase tables.
//
// Generated from the seed rows in `supabase_schema.sql`, so the tests exercise
// exactly the content the database is seeded with.
import 'package:bookaboo/features/books/data/models/book_model.dart';

final testCategories = <BookCategory>[
  BookCategory(id: 'animals', name: 'Animals', emoji: '🦁', color: 0xFFFFB443, imageAsset: 'assets/categories/animals.svg'),
  BookCategory(id: 'adventure', name: 'Adventure', emoji: '🗺️', color: 0xFF22B8A6, imageAsset: 'assets/categories/adventure.svg'),
  BookCategory(id: 'bedtime', name: 'Bedtime', emoji: '🌙', color: 0xFF5B4BE0, imageAsset: 'assets/categories/bedtime.svg'),
  BookCategory(id: 'fairy', name: 'Fairy Tales', emoji: '🏰', color: 0xFFFF7A6B, imageAsset: 'assets/categories/fairy.svg'),
  BookCategory(id: 'space', name: 'Space', emoji: '🚀', color: 0xFF4FB6F5, imageAsset: 'assets/categories/space.svg'),
  BookCategory(id: 'ocean', name: 'Ocean', emoji: '🐳', color: 0xFF0E86B8, imageAsset: 'assets/categories/ocean.svg'),
];

final testBooks = <Book>[
  Book(
    id: 'b1',
    title: 'Leo the Brave Little Lion',
    author: 'Maya Whiskers',
    coverAsset: 'assets/covers/b1.svg',
    coverEmoji: '🦁',
    coverColor: 0xFFFFB443,
    categoryId: 'animals',
    ageMin: 3,
    ageMax: 6,
    minutes: 5,
    rating: 4.8,
    description: 'Leo has a big mane but a tiny roar. Join him as he discovers that being brave comes in all sizes!',
    featured: true,
    pages: [
      BookPage(emoji: '🦁', text: 'Leo was the littlest lion in the whole savanna.'),
      BookPage(emoji: '🎈', text: 'His roar was so tiny it sounded like a squeaky balloon.'),
      BookPage(emoji: '🐘', text: 'One day, a baby elephant got stuck in the mud and cried for help.'),
      BookPage(emoji: '💪', text: 'Leo pushed and pulled with all his might until — POP! — out came the elephant.'),
      BookPage(emoji: '🎉', text: 'The whole savanna cheered. Leo learned that brave hearts can be any size.'),
    ],
  ),
  Book(
    id: 'b2',
    title: 'The Sleepy Moon',
    author: 'Nina Nightlight',
    coverAsset: 'assets/covers/b2.svg',
    coverEmoji: '🌙',
    coverColor: 0xFF5B4BE0,
    categoryId: 'bedtime',
    ageMin: 2,
    ageMax: 5,
    minutes: 4,
    rating: 4.9,
    description: 'The Moon is so sleepy tonight, but who will light up the sky? A gentle bedtime tale to drift off to.',
    featured: true,
    pages: [
      BookPage(emoji: '🌙', text: 'The Moon yawned a great big yawn. "I am so sleepy," she said.'),
      BookPage(emoji: '⭐', text: '"Rest, dear Moon," twinkled the stars. "We will keep watch tonight."'),
      BookPage(emoji: '🦉', text: 'The owls hooted a soft lullaby, hoo hoo, hoo hoo.'),
      BookPage(emoji: '☁️', text: 'A fluffy cloud tucked the Moon in like a cozy blanket.'),
      BookPage(emoji: '😴', text: 'Goodnight, Moon. Goodnight, stars. Goodnight, you.'),
    ],
  ),
  Book(
    id: 'b3',
    title: 'Zara\'s Rocket Ride',
    author: 'Cosmo Comet',
    coverAsset: 'assets/covers/b3.svg',
    coverEmoji: '🚀',
    coverColor: 0xFF4FB6F5,
    categoryId: 'space',
    ageMin: 4,
    ageMax: 8,
    minutes: 6,
    rating: 4.7,
    description: 'Zara builds a rocket out of cardboard and dreams — and tonight, it actually flies!',
    featured: true,
    pages: [
      BookPage(emoji: '📦', text: 'Zara built a rocket from a big cardboard box.'),
      BookPage(emoji: '🚀', text: 'She counted down: three... two... one... BLAST OFF!'),
      BookPage(emoji: '🪐', text: 'She zoomed past Saturn and waved at its sparkly rings.'),
      BookPage(emoji: '👽', text: 'A friendly alien named Bloop shared his moon-cheese sandwich.'),
      BookPage(emoji: '🛏️', text: 'Zara landed right back in her bed, just in time for dreams.'),
    ],
  ),
  Book(
    id: 'b4',
    title: 'The Whale Who Sang',
    author: 'Finn Splash',
    coverAsset: 'assets/covers/b4.svg',
    coverEmoji: '🐳',
    coverColor: 0xFF0E86B8,
    categoryId: 'ocean',
    ageMin: 3,
    ageMax: 7,
    minutes: 5,
    rating: 4.6,
    description: 'Wally the whale has the loveliest song in the sea, but he is too shy to sing it. Until one special day...',
    featured: false,
    pages: [
      BookPage(emoji: '🐳', text: 'Wally the whale loved to sing — but only when no one was listening.'),
      BookPage(emoji: '🐠', text: 'One day a little fish heard him and shouted, "More! More!"'),
      BookPage(emoji: '🦀', text: 'The crabs clicked their claws like castanets to join in.'),
      BookPage(emoji: '🎶', text: 'Soon the whole ocean was dancing to Wally\'s wonderful song.'),
      BookPage(emoji: '💙', text: 'Wally smiled. Sharing your song makes it twice as sweet.'),
    ],
  ),
  Book(
    id: 'b5',
    title: 'Pip the Penguin\'s Big Slide',
    author: 'Maya Whiskers',
    coverAsset: 'assets/covers/b5.svg',
    coverEmoji: '🐧',
    coverColor: 0xFF4FB6F5,
    categoryId: 'animals',
    ageMin: 2,
    ageMax: 5,
    minutes: 4,
    rating: 4.5,
    description: 'Pip is scared of the big icy slide. But with friends cheering, anything is possible. Wheee!',
    featured: false,
    pages: [
      BookPage(emoji: '🐧', text: 'Pip looked up at the big icy slide. It was VERY tall.'),
      BookPage(emoji: '😰', text: '"What if I wobble? What if I tumble?" Pip worried.'),
      BookPage(emoji: '📣', text: 'His friends cheered from below: "You can do it, Pip!"'),
      BookPage(emoji: '🛝', text: 'Pip took a deep breath and... WHEEEEE! Down he zoomed!'),
      BookPage(emoji: '🥳', text: '"Again! Again!" laughed Pip. Trying new things is fun!'),
    ],
  ),
  Book(
    id: 'b6',
    title: 'The Dragon Who Loved Pancakes',
    author: 'Rosie Tales',
    coverAsset: 'assets/covers/b6.svg',
    coverEmoji: '🐉',
    coverColor: 0xFFFF7A6B,
    categoryId: 'fairy',
    ageMin: 3,
    ageMax: 7,
    minutes: 6,
    rating: 4.8,
    description: 'Darcy the dragon burns every pancake with her fiery sneezes. Can the village kids help her flip the perfect one?',
    featured: false,
    pages: [
      BookPage(emoji: '🐉', text: 'Darcy the dragon loved pancakes more than anything.'),
      BookPage(emoji: '🔥', text: 'But every time she cooked — ACHOO! — her sneeze burnt them to a crisp.'),
      BookPage(emoji: '🧒', text: 'The village kids had an idea: "Let US cook, and YOU flip!"'),
      BookPage(emoji: '🥞', text: 'Darcy flipped the pancake so high it did three somersaults!'),
      BookPage(emoji: '🍯', text: 'They all shared a giant pancake feast. Teamwork tastes delicious.'),
    ],
  ),
  Book(
    id: 'b7',
    title: 'Map to the Giggle Tree',
    author: 'Sunny Trails',
    coverAsset: 'assets/covers/b7.svg',
    coverEmoji: '🗺️',
    coverColor: 0xFF22B8A6,
    categoryId: 'adventure',
    ageMin: 4,
    ageMax: 8,
    minutes: 7,
    rating: 4.7,
    description: 'X marks the spot where giggles grow! Follow the squiggly map through jungles and rivers to the funniest tree on Earth.',
    featured: false,
    pages: [
      BookPage(emoji: '🗺️', text: 'Milo found a squiggly map under his pillow. "To the Giggle Tree!" it said.'),
      BookPage(emoji: '🌴', text: 'He tiptoed through the tickle-jungle, where the leaves giggled softly.'),
      BookPage(emoji: '🛶', text: 'He paddled across the chuckle-river in a banana boat.'),
      BookPage(emoji: '🌳', text: 'There it was — the Giggle Tree, wobbling with laughter!'),
      BookPage(emoji: '😂', text: 'Milo laughed until his tummy hurt, and took a giggle home for you.'),
    ],
  ),
  Book(
    id: 'b8',
    title: 'Twinkle the Shy Star',
    author: 'Nina Nightlight',
    coverAsset: 'assets/covers/b8.svg',
    coverEmoji: '⭐',
    coverColor: 0xFFFFB443,
    categoryId: 'bedtime',
    ageMin: 2,
    ageMax: 5,
    minutes: 4,
    rating: 4.6,
    description: 'Twinkle hides behind clouds because she thinks her light is too small. A cozy tale about shining your own way.',
    featured: false,
    pages: [
      BookPage(emoji: '⭐', text: 'Twinkle was the smallest star in the night sky.'),
      BookPage(emoji: '☁️', text: 'She hid behind a cloud. "My light is too tiny," she sighed.'),
      BookPage(emoji: '🐞', text: 'Down below, a lost ladybug whispered, "I wish I could find my way home."'),
      BookPage(emoji: '✨', text: 'Twinkle peeked out and shone with all her heart — just enough light!'),
      BookPage(emoji: '🏡', text: 'The ladybug found her way home. Even tiny lights are mighty.'),
    ],
  ),
  Book(
    id: 'b9',
    title: 'The Mermaid\'s Lost Comb',
    author: 'Finn Splash',
    coverAsset: 'assets/covers/b9.svg',
    coverEmoji: '🧜‍♀️',
    coverColor: 0xFFF472B6,
    categoryId: 'ocean',
    ageMin: 4,
    ageMax: 8,
    minutes: 6,
    rating: 4.5,
    description: 'Marina the mermaid lost her pearly comb in the kelp forest. Good thing the sea is full of helpful friends!',
    featured: false,
    pages: [
      BookPage(emoji: '🧜‍♀️', text: 'Marina the mermaid lost her pearly comb. Oh no!'),
      BookPage(emoji: '🌿', text: 'She searched the swishy kelp forest, up and down.'),
      BookPage(emoji: '🐙', text: 'Ollie the octopus helped — eight arms find things fast!'),
      BookPage(emoji: '🦞', text: 'A lobster found it being used as a tiny rake. Oops!'),
      BookPage(emoji: '💖', text: 'Marina combed her hair and gave everyone seaweed high-fives.'),
    ],
  ),
  Book(
    id: 'b10',
    title: 'Benny Bear Goes to School',
    author: 'Maya Whiskers',
    coverAsset: 'assets/covers/b10.svg',
    coverEmoji: '🐻',
    coverColor: 0xFFB08968,
    categoryId: 'animals',
    ageMin: 3,
    ageMax: 6,
    minutes: 5,
    rating: 4.7,
    description: 'It is Benny\'s first day of forest school. Butterflies in his tummy — and a new best friend waiting.',
    featured: false,
    pages: [
      BookPage(emoji: '🐻', text: 'Benny Bear held his honey sandwich tight. First day of school!'),
      BookPage(emoji: '🦋', text: 'His tummy felt full of butterflies. Flutter, flutter.'),
      BookPage(emoji: '🐰', text: 'A little rabbit waved. "Want to share my carrot cake?"'),
      BookPage(emoji: '🎨', text: 'They painted, sang, and built a leaf fort together.'),
      BookPage(emoji: '🌟', text: 'Benny skipped home. "School is my new favorite adventure!"'),
    ],
  ),
  Book(
    id: 'b11',
    title: 'The Castle of Cupcakes',
    author: 'Rosie Tales',
    coverAsset: 'assets/covers/b11.svg',
    coverEmoji: '🏰',
    coverColor: 0xFFF472B6,
    categoryId: 'fairy',
    ageMin: 3,
    ageMax: 7,
    minutes: 6,
    rating: 4.6,
    description: 'A castle with frosting towers and sprinkle bridges? Princess Poppy invites everyone to the sweetest feast ever.',
    featured: false,
    pages: [
      BookPage(emoji: '🏰', text: 'Princess Poppy lived in a castle made of cupcakes.'),
      BookPage(emoji: '🌧️', text: 'One rainy day, the frosting towers began to slide!'),
      BookPage(emoji: '🐿️', text: 'Poppy called every squirrel, mouse and bird to help.'),
      BookPage(emoji: '🍓', text: 'They patched the walls with strawberries and sprinkles.'),
      BookPage(emoji: '🧁', text: 'Then they ate the leftovers, of course. Best. Feast. Ever.'),
    ],
  ),
  Book(
    id: 'b12',
    title: 'Rover on the Red Planet',
    author: 'Cosmo Comet',
    coverAsset: 'assets/covers/b12.svg',
    coverEmoji: '🛸',
    coverColor: 0xFFFF8A5B,
    categoryId: 'space',
    ageMin: 4,
    ageMax: 8,
    minutes: 5,
    rating: 4.4,
    description: 'Beep boop! Rover the robot explores Mars and finds something nobody expected: a very red, very bouncy ball.',
    featured: false,
    pages: [
      BookPage(emoji: '🤖', text: 'Rover the robot rolled across the red sands of Mars.'),
      BookPage(emoji: '🔴', text: 'Beep! His scanner found something round and bouncy.'),
      BookPage(emoji: '⛰️', text: 'He followed it bouncing over craters and dusty hills.'),
      BookPage(emoji: '🛸', text: 'It bounced right into a tiny spaceship — it was a spaceball!'),
      BookPage(emoji: '🏓', text: 'Rover and the aliens played catch until the stars came out.'),
    ],
  ),
];
